### ISSUE TITLE
Branch for mickledore

### ISSUE THREAD

**Issue by shr-project** [shift-left-test/meta-shift#9]
https://github.com/shift-left-test/meta-shift/commit/a870b936a71e47a3d153fa5c4c9f3e102c105026 makes master branch incompatible with latest stable release mickledore. Do you plan to branch mickledore before this commit?

**Comment by sung-gon-kim** [comment]
Yes. We are aware of the issue, and are working on releasing the mickledore branch. It will appear soon. Thanks.
